syntax = "proto3";

package example;

option go_package = "github.com/paskozdilar/buf-report-grpc-gateway/example";

import "google/protobuf/empty.proto";
import "google/api/annotations.proto";

service ExampleService {
  rpc UnaryBody (google.protobuf.Empty) returns (ExampleResponse) {
    option (google.api.http) = {
      post: "/example/v1/UnaryBody";
      body: "*";
    };
  }

  rpc UnaryNoBody (google.protobuf.Empty) returns (ExampleResponse) {
    option (google.api.http) = {
      post: "/example/v1/UnaryNoBody";
    };
  }

  rpc ServerStreamBody (google.protobuf.Empty) returns (stream ExampleResponse) {
    option (google.api.http) = {
      post: "/example/v1/ServerStreamBody";
      body: "*";
    };
  }

  rpc ServerStreamNoBody (google.protobuf.Empty) returns (stream ExampleResponse) {
    option (google.api.http) = {
      post: "/example/v1/ServerStreamNoBody";
    };
  }
}

message ExampleResponse {
  string id = 1;
  string name = 2;
}
