// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: example/example.proto

package example

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_example_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExampleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_example_example_proto protoreflect.FileDescriptor

const file_example_example_proto_rawDesc = "" +
	"\n" +
	"\x15example/example.proto\x12\aexample\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"5\n" +
	"\x0fExampleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xb6\x03\n" +
	"\x0eExampleService\x12_\n" +
	"\tUnaryBody\x12\x16.google.protobuf.Empty\x1a\x18.example.ExampleResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/example/v1/UnaryBody\x12`\n" +
	"\vUnaryNoBody\x12\x16.google.protobuf.Empty\x1a\x18.example.ExampleResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/example/v1/UnaryNoBody\x12o\n" +
	"\x10ServerStreamBody\x12\x16.google.protobuf.Empty\x1a\x18.example.ExampleResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/example/v1/ServerStreamBody0\x01\x12p\n" +
	"\x12ServerStreamNoBody\x12\x16.google.protobuf.Empty\x1a\x18.example.ExampleResponse\"&\x82\xd3\xe4\x93\x02 \"\x1e/example/v1/ServerStreamNoBody0\x01B8Z6github.com/paskozdilar/buf-report-grpc-gateway/exampleb\x06proto3"

var (
	file_example_example_proto_rawDescOnce sync.Once
	file_example_example_proto_rawDescData []byte
)

func file_example_example_proto_rawDescGZIP() []byte {
	file_example_example_proto_rawDescOnce.Do(func() {
		file_example_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_example_proto_rawDesc), len(file_example_example_proto_rawDesc)))
	})
	return file_example_example_proto_rawDescData
}

var file_example_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_example_proto_goTypes = []any{
	(*ExampleResponse)(nil), // 0: example.ExampleResponse
	(*emptypb.Empty)(nil),   // 1: google.protobuf.Empty
}
var file_example_example_proto_depIdxs = []int32{
	1, // 0: example.ExampleService.UnaryBody:input_type -> google.protobuf.Empty
	1, // 1: example.ExampleService.UnaryNoBody:input_type -> google.protobuf.Empty
	1, // 2: example.ExampleService.ServerStreamBody:input_type -> google.protobuf.Empty
	1, // 3: example.ExampleService.ServerStreamNoBody:input_type -> google.protobuf.Empty
	0, // 4: example.ExampleService.UnaryBody:output_type -> example.ExampleResponse
	0, // 5: example.ExampleService.UnaryNoBody:output_type -> example.ExampleResponse
	0, // 6: example.ExampleService.ServerStreamBody:output_type -> example.ExampleResponse
	0, // 7: example.ExampleService.ServerStreamNoBody:output_type -> example.ExampleResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_example_proto_init() }
func file_example_example_proto_init() {
	if File_example_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_example_proto_rawDesc), len(file_example_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_example_proto_goTypes,
		DependencyIndexes: file_example_example_proto_depIdxs,
		MessageInfos:      file_example_example_proto_msgTypes,
	}.Build()
	File_example_example_proto = out.File
	file_example_example_proto_goTypes = nil
	file_example_example_proto_depIdxs = nil
}
