// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: services/v1/api.proto

package v1

import (
	v1 "github.com/paskozdilar/bug-report-grpc-gateway/src/proto/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_v1_api_proto protoreflect.FileDescriptor

const file_services_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x15services/v1/api.proto\x12\vservices.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/v1/app.proto2\xac\x01\n" +
	"\x03API\x12R\n" +
	"\aGetApps\x12\x16.google.protobuf.Empty\x1a\x14.common.v1.AppsBasic\"\x19\x82\xd3\xe4\x93\x02\x13b\x04apps\x12\v/api/v1/app\x12Q\n" +
	"\rGetAppDetails\x12\x11.common.v1.AppKey\x1a\x0e.common.v1.App\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/app/{app_key}BFZDgithub.com/paskozdilar/bug-report-grpc-gateway/src/proto/services/v1b\x06proto3"

var file_services_v1_api_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*v1.AppKey)(nil),     // 1: common.v1.AppKey
	(*v1.AppsBasic)(nil),  // 2: common.v1.AppsBasic
	(*v1.App)(nil),        // 3: common.v1.App
}
var file_services_v1_api_proto_depIdxs = []int32{
	0, // 0: services.v1.API.GetApps:input_type -> google.protobuf.Empty
	1, // 1: services.v1.API.GetAppDetails:input_type -> common.v1.AppKey
	2, // 2: services.v1.API.GetApps:output_type -> common.v1.AppsBasic
	3, // 3: services.v1.API.GetAppDetails:output_type -> common.v1.App
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_v1_api_proto_init() }
func file_services_v1_api_proto_init() {
	if File_services_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_v1_api_proto_rawDesc), len(file_services_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_api_proto_goTypes,
		DependencyIndexes: file_services_v1_api_proto_depIdxs,
	}.Build()
	File_services_v1_api_proto = out.File
	file_services_v1_api_proto_goTypes = nil
	file_services_v1_api_proto_depIdxs = nil
}
