// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/app.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppKey) Reset() {
	*x = AppKey{}
	mi := &file_common_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppKey) ProtoMessage() {}

func (x *AppKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppKey.ProtoReflect.Descriptor instead.
func (*AppKey) Descriptor() ([]byte, []int) {
	return file_common_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppKey) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type AppBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppBasic) Reset() {
	*x = AppBasic{}
	mi := &file_common_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppBasic) ProtoMessage() {}

func (x *AppBasic) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppBasic.ProtoReflect.Descriptor instead.
func (*AppBasic) Descriptor() ([]byte, []int) {
	return file_common_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppBasic) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *AppBasic) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppBasic) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AppsBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppBasic            `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppsBasic) Reset() {
	*x = AppsBasic{}
	mi := &file_common_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppsBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppsBasic) ProtoMessage() {}

func (x *AppsBasic) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppsBasic.ProtoReflect.Descriptor instead.
func (*AppsBasic) Descriptor() ([]byte, []int) {
	return file_common_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppsBasic) GetApps() []*AppBasic {
	if x != nil {
		return x.Apps
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Vendor        string                 `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_common_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_common_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *App) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *App) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *App) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *App) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *App) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_common_v1_app_proto protoreflect.FileDescriptor

const file_common_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x13common/v1/app.proto\x12\tcommon.v1\"!\n" +
	"\x06AppKey\x12\x17\n" +
	"\aapp_key\x18\x01 \x01(\tR\x06appKey\"X\n" +
	"\bAppBasic\x12\x17\n" +
	"\aapp_key\x18\x01 \x01(\tR\x06appKey\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"4\n" +
	"\tAppsBasic\x12'\n" +
	"\x04apps\x18\x01 \x03(\v2\x13.common.v1.AppBasicR\x04apps\"\xa7\x01\n" +
	"\x03App\x12\x17\n" +
	"\aapp_key\x18\x01 \x01(\tR\x06appKey\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x05 \x01(\tR\x06vendor\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescriptionBDZBgithub.com/paskozdilar/bug-report-grpc-gateway/src/proto/common/v1b\x06proto3"

var (
	file_common_v1_app_proto_rawDescOnce sync.Once
	file_common_v1_app_proto_rawDescData []byte
)

func file_common_v1_app_proto_rawDescGZIP() []byte {
	file_common_v1_app_proto_rawDescOnce.Do(func() {
		file_common_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_app_proto_rawDesc), len(file_common_v1_app_proto_rawDesc)))
	})
	return file_common_v1_app_proto_rawDescData
}

var file_common_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_v1_app_proto_goTypes = []any{
	(*AppKey)(nil),    // 0: common.v1.AppKey
	(*AppBasic)(nil),  // 1: common.v1.AppBasic
	(*AppsBasic)(nil), // 2: common.v1.AppsBasic
	(*App)(nil),       // 3: common.v1.App
}
var file_common_v1_app_proto_depIdxs = []int32{
	1, // 0: common.v1.AppsBasic.apps:type_name -> common.v1.AppBasic
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_app_proto_init() }
func file_common_v1_app_proto_init() {
	if File_common_v1_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_app_proto_rawDesc), len(file_common_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_app_proto_goTypes,
		DependencyIndexes: file_common_v1_app_proto_depIdxs,
		MessageInfos:      file_common_v1_app_proto_msgTypes,
	}.Build()
	File_common_v1_app_proto = out.File
	file_common_v1_app_proto_goTypes = nil
	file_common_v1_app_proto_depIdxs = nil
}
